### ISSUE TITLE
midterm-slicing.py is ready

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#10]

**Comment by cethenmc** [comment]
Nice work overall, but I again ran into the interpreter issue (same path as the Midterm-if section) (2 pts).  Similar to the Midterm-if section you completed, please do not use the absolute path when opening the file.  We intentionally ask you to put them in same directory so that you can use just the file name.  Remember, I won't have the same absolute path in my environment.  We asked questions in 4a through 4e in a specific way, so you would show your searches from the end of the file with negative numbers.  In var_a, var_c, and var_e, you intermingled (2 pts).  I like the notation you used for the for loop in your line 22, just because we did not teach it that way, and you must have found it on your own.  However, it was unnecessary (extra processing) because you already had quote as string in line 21.  You could have added a .replace('\n',' ') at the end of line 21 and rid your script of lines 22 and 23 completely (1 pt).  29/34.
