### ISSUE TITLE
Week 5 Complete and ready for grading

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#4]
I hope I did the last part right.  Please let me know if anything is amiss.

**Comment by cethenmc** [comment]
Please follow the directions carefully.  You have so many pint outs to the terminal and I should not see that many.  Do NOT print out to the screen anything except what is specifically requested by the assignment.  Please resubmit ASAP.

**Comment by ndaley-matc** [comment]
I have removed the printout of the lines.  Although the instructions statred to "DO NOT print the contents of the file."  The contents of the file not being printed out, only one line for each password in the file and counts for each line.  

I have reduced the printout to just a few sentences.  Please let me know if this was more what you were looking for.

**Comment by ndaley-matc** [comment]
Chris, 

I could appreciate your position.  That all makes sense.  Thanks for the feedback.  I'll check back from time to time to see the results.

**Comment by ndaley-matc** [comment]
Chris, 

I have made the corrections you asked for on Week 5.  It is ready for grading.

**Comment by ndaley-matc** [comment]
This should be corrected now.

**Comment by cethenmc** [comment]
Hi, Nathan.  Thanks for meeting yesterday.  Like I said, your length definitions are not wrong, so you will receive full credit.  However, I really would have liked to see your addition to the definition in 1B also mention that since the read() object returns a string, and each item in a string is a character, that the len() in context of the file is that it returns the number of characters in the file (including spaces).

For 2B, because readlines() returns a List object with each item being a unique line from your file, the len() returns the number of lines written in your file.

I hope this additional explanation is helpful to you.  Full credit earned!  Nice job!
