### ISSUE TITLE
Week 7 Dictionaries Ready for grading.

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#7]
Week 7 dictionaries ready for grading.

**Comment by cethenmc** [comment]
Hi, Nathan.  Nice attempt.  You did figure out a neat way to create a dictionary, and sometimes when we try to make things very organized we overcomplicate a little.

In this assignment, we were looking for the use of the functions learned (keys(), values(), and items()) and use of flow control and an in statement to check existence.  Knowing these tips could you try again?

Also, to reduce the complexity, perhaps you want to make this your answer to #1 to get you started.

domainToIPMappingDict = {
    "server1.testlab.com":"192.168.1.10",
    "server2.testlab.com":"192.168.1.11",
    "server3.testlab.com":"192.168.1.12",
    "server4.testlab.com":"192.168.1.13",
    "server5.testlab.com":"192.168.1.14",
    "server6.testlab.com":"192.168.1.15"
}

I will record 4 of 8 for now, just because I like how you challenged yourself.  As with other assignments, please feel free to resubmit for full credit.

**Comment by ndaley-matc** [comment]
I made the adjustments as you request.

**Comment by cethenmc** [comment]
Sorry, Nathan, I did not articulate clearly enough.  After switching the first to what I showed you, I would now like you to re-answer #2 through 7 using the new dictionary.  Thanks for your patience.  ~Chris

**Comment by ndaley-matc** [comment]
Chris, 

I think I have the corrections you asked for if I'm understanding the ask of #2 through #7.  Let me know or we can speak tonight.

**Comment by ndaley-matc** [comment]
I should have this corrected now.

**Comment by cethenmc** [comment]
Thanks for meeting with me today.  I hope it was helpful for you.  Nice work on this one.
