### ISSUE TITLE
midterm-if.py is ready

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#8]

**Comment by ndaley-matc** [comment]
Ready for grading.

**Comment by cethenmc** [comment]
The first issue I ran into when executing ./midterm-if.py from the command line was "user/bin/env:  bad interpreter: No such file or directory."  This should have been tested running at the command line level before submitting. (2 pts).  There are two errors in your shebang line.  Can you find them?  Secondly, if you could, when your text file is stored in the same directory as your script, please use the filename instead of the absolute path.  When I run your script, I will not have the same absolute path.  No points deducted, but perhaps on the final.  I assume you could not recall a method to extract the line number as requested.  What if the lines had gaps in IDs, weren't sorted, or their IDs started with 1000?  Move Lanie Whiteland's record down between IDs 13 and 14, and your total would end up being 2427.  Extracting the line number (2 pts) and converting it to an int (2 pts) [which was a hint to help you know what you might use to extract] were two required steps.  Your score for this part is 27/33.
