### ISSUE TITLE
midterm-jpark.py is ready

### ISSUE THREAD

**Issue by ndaley-matc** [madisoncollege-it-programs/python-scripting-ndaley-matc#9]

**Comment by ndaley-matc** [comment]
Ready for grading.

**Comment by cethenmc** [comment]
Overall, nicely done.  Ran into an immediate hang up with the interpreter in this file also.  Ironically, you did not copy and paste from the part 1 script because the path of the interpreter is different on this file than the first midterm part (1 pt).    For each dictionary key, you made its value a single value set.  This is why many of your prints end up with curly brackets.  As such, you were printing out a set instead of a string. (1 pt).  Your score for this part is 31/33.
